"""added startDate to FixedCosts

Revision ID: 1a08ea227e1a
Revises: 3ef9c134e20c
Create Date: 2026-05-26 15:57:32.848258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a08ea227e1a'
down_revision: Union[str, Sequence[str], None] = '3ef9c134e20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_costs', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_costs', 'start_date')
    # ### end Alembic commands ###
