"""added uniqueConstraint in Categories model

Revision ID: 3ef9c134e20c
Revises: 90e2c268d837
Create Date: 2026-05-25 20:57:51.172714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef9c134e20c'
down_revision: Union[str, Sequence[str], None] = '90e2c268d837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_category_name_per_user', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_name_per_user', 'categories', type_='unique')
    # ### end Alembic commands ###
