"""added uniqueConstraint in Budgets model

Revision ID: 90e2c268d837
Revises: f9417adf46d7
Create Date: 2026-05-25 20:54:13.002757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e2c268d837'
down_revision: Union[str, Sequence[str], None] = 'f9417adf46d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_budget_per_month', 'budgets', ['user_id', 'category_id', 'budget_month', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_budget_per_month', 'budgets', type_='unique')
    # ### end Alembic commands ###
