"""added nullable statements to models

Revision ID: e02611973b31
Revises: 1a08ea227e1a
Create Date: 2026-05-26 16:13:55.054072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e02611973b31'
down_revision: Union[str, Sequence[str], None] = '1a08ea227e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'budget_month',
               existing_type=postgresql.ENUM('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='budgetmonth'),
               nullable=False)
    op.alter_column('budgets', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'limit_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('categories', 'category_type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', name='categorytype'),
               nullable=False)
    op.alter_column('fixed_costs', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('fixed_costs', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('fixed_costs', 'interval_unit',
               existing_type=postgresql.ENUM('DAY', 'WEEK', 'MONTH', 'YEAR', name='intervalunitenum'),
               nullable=False)
    op.alter_column('fixed_costs', 'interval_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fixed_costs', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('transactions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', 'INITIAL', name='transactiontype'),
               nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', 'INITIAL', name='transactiontype'),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('transactions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('fixed_costs', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fixed_costs', 'interval_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixed_costs', 'interval_unit',
               existing_type=postgresql.ENUM('DAY', 'WEEK', 'MONTH', 'YEAR', name='intervalunitenum'),
               nullable=True)
    op.alter_column('fixed_costs', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('fixed_costs', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('categories', 'category_type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', name='categorytype'),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('budgets', 'limit_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('budgets', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('budgets', 'budget_month',
               existing_type=postgresql.ENUM('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='budgetmonth'),
               nullable=True)
    # ### end Alembic commands ###
