"""added checkConstraint for interval_value in FixedCosts

Revision ID: f9417adf46d7
Revises: 8faffb1b1970
Create Date: 2026-05-25 18:48:53.364805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9417adf46d7'
down_revision: Union[str, Sequence[str], None] = '8faffb1b1970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_interval_value_positive",
        "fixed_costs",
        "interval_value > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_interval_value_positive", "fixed_costs")
    # ### end Alembic commands ###
